apiVersion: v1
kind: Service
metadata:
  name: {{ include "syphon.fullname" . }}
  labels:
    {{- include "syphon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: tcp
    - port: {{ .Values.service.port }}
      protocol: udp
      name: udp
  selector:
    {{- include "syphon.selectorLabels" . | nindent 4 }}
